### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by fg1998** [abelykh0/esp32-z80emu#1]
Compiling Error - PlatformIO VSCode win10
Using FABGl 0.9.0 (current)

Some directions ?

------------------CUT HERE-------------------
Compiling .pio\build\pico32\lib738\FabGL@0.8.0\canvas.cpp.o
In file included from lib/Display/Screen.h:5:0,
                 from include/Emulator.h:4,
                 from src\emulator.cpp:1:
lib/Display/VideoController.h:13:1: error: expected class-name before '{' token
 {
 ^
In file included from lib/Display/Screen.h:5:0,
                 from include/Emulator.h:4,
                 from src\FileSystem.cpp:7:
lib/Display/VideoController.h:13:1: error: expected class-name before '{' token
 {
 ^
*** [.pio\build\pico32\src\FileSystem.cpp.o] Error 1
src\emulator.cpp: In function 'void startKeyboard()':
src\emulator.cpp:53:2: error: 'quickCheckHardware' is not a member of 'fabgl::Mouse'
  Mouse::quickCheckHardware();
  ^
*** [.pio\build\pico32\src\emulator.cpp.o] Error 1
In file included from lib/Display/Screen.h:5:0,
                 from include/emulator.h:4,
                 from src\main.cpp:3:
lib/Display/VideoController.h:13:1: error: expected class-name before '{' token
 {
 ^
*** [.pio\build\pico32\src\main.cpp.o] Error 1

**Comment by abelykh0** [comment]
Unfortunately ,this one requires the latest (unreleased) FabGL because I am using a new VGADirectController .
