### ISSUE TITLE
Fix for bad AY-3-891x sound

### ISSUE THREAD

**Issue by dcrespo3d** [abelykh0/esp32-z80emu#3]
Hello,

I have tested your emulator and it has sound, but the melodies are reversed in pitch.

The AY-3-891x chip "pitch" parameter corresponds to the wave period, not its frequency. Your code passes directly pitch as frequency, which is not correct.

For an AY running at 4MHz, reference frequency is 125000 Hz. But on a Spectrum 128K, it runs at 3.5469MHz, so the frequency is 125000 * 3.5469 / 4 = 110840.

You should substitute line 141 in /lib/Sound/ay3-8912-state.cpp
from
`_channel[channel].setFrequency(this->channelFrequency[channel]);`
to
`_channel[channel].setFrequency(fixPitch(this->channelFrequency[channel]));`

and defining somewhere in your code a fixPitch function like this:
```
inline int fixPitch(int p)
{
#define FREQUENCY_REFERENCE 110840
	int fixed = (p > 0) ? (FREQUENCY_REFERENCE / p) : 0;
	return fixed;
}
```

Regards,
    David

**Comment by abelykh0** [comment]
Thank you for your suggestion. Can you please submit a pull request, I will merge it.

**Comment by abelykh0** [comment]
Fixed. However other things are still broken, I am in the middle of big refactoring

**Comment by abelykh0** [comment]
Everything should work now
