### ISSUE TITLE
Error when loading from SD card

### ISSUE THREAD

**Issue by azesmbog** [abelykh0/esp32-z80emu#4]
Привет.
С последними версиями библиотек  в PlatformIO проект собирается, но не работает с SD-картами.
в терминале такая ошибка:
[ 11940][E][sd_diskio.cpp:796] sdcard_mount(): esp_vfs_fat_register failed 0x(101)
Возможно ли перепроверить и исправить по возможности??

**Comment by abelykh0** [comment]
I changed it temporarily to 48K. Looks like it doesn't fit any more. Will take a look later. The easiest is just to use PSRAM, but I will try to see how much is needed. I also fixed a bug which prevented reading files in 48K mode. You can use /roms/48.rom. Please let me know how it goes. Thanks for reporting!

**Comment by azesmbog** [comment]
Какие то изменения есть.
`before zx_reset()
Z80Environment::Initialize()
before loop
Free heap 32BIT: 5400, free heap 8BIT: 92868
file count=7
in the middle of repeat`
Теперь ROM zx48 загружается, файлы на диске видит, но снапшоты не запускает.
Но... но по моей просьбе  [ackerman](http://retrowiki.es/memberlist.php?mode=viewprofile&u=5969)
создал 4 прекомпилированных бинарника, они запускают тестовый файл демо, вернее с cpu от  Lin Ke-Fong's  работает лучше всего и Andre Weissflog's core тоже работало, но немного тормознутее.
Теперь же файл видят, но не работает, или сбрасывается, или виснет.

**Comment by abelykh0** [comment]
Странно, у меня все 48K снапшоты запускаются.

**Comment by azesmbog** [comment]
Сильное заявление. :))
Давайте все мои запустим? Ну хотя бы некоторые, тестовые.
https://drive.google.com/file/d/1_p9J-qIqi-5uX0pIDlkJT_ITs9jAEDU9/view?usp=share_link
aeonnano - крошечная демка,  так то 128-я, но даже в режиме zx48 в эмуляторах и то работает.  В прекомпилированных версиях (в архиве присутствуют) - работает в двух ядрах.
Ну и все остальные, какие то 48-е, какие то 128-е. В эмулях работают 100%.
Тут же что то пытается работать.
Тест звука приложил.  Даже если и запустится - то огибающих и шумов нет напрочь. в демо AEON выражается в периодическом отсутствии какого то либо звука.

**Comment by abelykh0** [comment]
Сильное заявление. :))
Нет, конечно этому коду далеко до качества коммерческого продукта - все-таки это хобби проект :)

Давайте все мои запустим? Ну хотя бы некоторые, тестовые.
aeonnano - у меня тоже падает, посмотрю почему
по поводу звука - у меня не все эмулируется, посмотрю тоже. FYI https://github.com/abelykh0/esp32-z80emu/blob/main/src/ay3-8912-state.cpp?plain=1#L110

**Comment by abelykh0** [comment]
Еще и beeper почему-то перестал работать. Там вообще буквально 3 строчки кода :(

**Comment by azesmbog** [comment]
я понимаю , что это хобби-проект, для себя любимого. Без всяких обид! :))
Если бипер будешь делать, то сделай вывод звука и через TapeOut. В реалах это работает, звук слышно, но раза в два тише, чем основной. Тестировать все в той же AYtest.0.2

**Comment by abelykh0** [comment]
Я забил на Ардуино, теперь все в основном работает, кроме BEEPER и тех каналов генератора AY3-8912, которые мне лень делать (6 noisePitch; 11,12,13 envelope). BEEPER я постараюсь сделать.

**Comment by abelykh0** [comment]
OK, I am closing this one. Will keep working on Beeper.
